version: "3"
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432
    environment:
      - PGDATA=/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - 6380:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@db:5432/yourdbname
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app
    command: ["/bin/bash", "/worker-start.sh"]

